# Generated by Django 5.1 on 2024-08-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_scientists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express', models.TextField()),
            ],
        ),
    ]
