# Generated by Django 5.1 on 2024-08-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_expressions'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
