# Generated by Django 5.1 on 2024-08-22 06:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provensiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provensiya', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='scientists',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammatical', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('lexical', models.CharField(max_length=200)),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sentences', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('provensiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.provensiya')),
            ],
        ),
    ]
