# Generated by Django 5.1 on 2024-08-22 07:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_provensiya_alter_news_description_alter_news_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='sentences',
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.dictionary')),
            ],
        ),
    ]
